Update docker-compose.yml fixes #16 invalid boolean valud
Fixes:
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.strapi-v4.environment.DATABASE_SSL contains false, which is an invalid type, it should be a string, number, or a null